import os
import json
import requests
import re
import subprocess

API_KEY = os.environ.get("LLM_API_KEY")
GH_TOKEN = os.environ.get("GH_TOKEN")
PR_NUMBER = os.environ.get("PR_NUMBER")
REPO_NAME = os.environ.get("REPO_NAME")
# GitHub Actions sets this environment variable automatically
HEAD_REF = os.environ.get("GITHUB_HEAD_REF")

LLM_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

def read_file(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def run_command(command):
    """Utility to run shell commands (like git)"""
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Command failed: {command}\nError: {result.stderr}")
    return result.returncode == 0

def main():
    if not API_KEY:
        print("Error: LLM_API_KEY is missing.")
        return

    master_agent_prompt = read_file(".github/scripts/master-reviewer-agent.md")

    try:
        pr_diff = read_file("pr_diff.patch")
    except FileNotFoundError:
        print("No diff found. Skipping review.")
        return

    print("Sending code to Gemini Agent for review & fixing...")

    system_instruction = f"{master_agent_prompt}\n\nReview the following code diff. If you find issues, output the complete corrected file using the <file_update> tag."
    user_prompt = f"Here is the git diff:\n\n```diff\n{pr_diff}\n```"

    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": API_KEY
    }

    payload = {
        "systemInstruction": {"parts": [{"text": system_instruction}]},
        "contents": [{"role": "user", "parts": [{"text": user_prompt}]}],
        "generationConfig": {"temperature": 0.1}
    }

    response = requests.post(LLM_API_URL, headers=headers, json=payload)
    response_data = response.json()

    try:
        review_comment = response_data["candidates"][0]["content"]["parts"][0]["text"]
    except KeyError:
        print("Error parsing Gemini response.")
        return

    # --- NEW: AUTO-FIX LOGIC ---
    print("Searching for auto-fixes in AI response...")
    # Regex to find <file_update path="..."> ...content... </file_update>
    pattern = r'<file_update path="(.*?)">(.*?)</file_update>'
    matches = re.findall(pattern, review_comment, re.DOTALL)

    fixes_applied = False
    for filepath, new_content in matches:
        filepath = filepath.strip()
        new_content = new_content.strip()

        # 1. Overwrite the local file with the AI's new code
        print(f"Applying fix to: {filepath}")
        try:
            with open(filepath, 'w') as f:
                f.write(new_content)
            fixes_applied = True
        except Exception as e:
            print(f"Failed to write file {filepath}: {e}")

    # 2. If fixes were applied, commit and push them
    if fixes_applied:
        print("Committing and pushing fixes to the PR branch...")
        run_command('git config --global user.name "AI Code Agent"')
        run_command('git config --global user.email "ai-agent@example.com"')

        # Checkout the PR branch (Actions checks out a detached HEAD by default)
        run_command(f'git checkout {HEAD_REF}')

        run_command('git add .')
        run_command('git commit -m "🤖 AI Agent Auto-Fix: Resolved code review findings"')
        run_command(f'git push origin {HEAD_REF}')
        print("✅ Auto-fixes pushed successfully!")
    else:
        print("No auto-fixes generated by the AI.")
    # ---------------------------

    print("Posting review comment to GitHub PR...")
    gh_headers = {
        "Authorization": f"token {GH_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    gh_url = f"https://api.github.com/repos/{REPO_NAME}/issues/{PR_NUMBER}/comments"

    # Optional: clean the XML tags out of the comment so it looks nice on GitHub
    clean_comment = re.sub(pattern, '*Auto-fix applied and pushed to branch.*', review_comment, flags=re.DOTALL)

    requests.post(gh_url, headers=gh_headers, json={"body": clean_comment})

if __name__ == "__main__":
    main()